services:
  - type: web
    name: davd-dash-app
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --timeout 600 app:server
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.0"
